<a href="https://colab.research.google.com/github/jiteshpabla/burrito-visualization/blob/main/burrito_preproccesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import string

In [ ]:
df = pd.read_csv("Burrito.csv")
df

                     Location        Burrito       Date  ... Avocado Corn Zucchini
0          Donato's taco shop    California   1/18/2016  ...     NaN  NaN      NaN
1        Oscar's Mexican food    California   1/24/2016  ...     NaN  NaN      NaN
2        Oscar's Mexican food       Carnitas  1/24/2016  ...     NaN  NaN      NaN
3        Oscar's Mexican food    Carne asada  1/24/2016  ...     NaN  NaN      NaN
4                Pollos Maria     California  1/27/2016  ...     NaN  NaN      NaN
..                        ...            ...        ...  ...     ...  ...      ...
418  Valentine's Mexican Food      Al Pastor  8/27/2019  ...     NaN  NaN      NaN
419  Valentine's Mexican Food  Chile Relleno  8/27/2019  ...     NaN  NaN      NaN
420  Valentine's Mexican Food     California  8/27/2019  ...     NaN  NaN      NaN
421  Valentine's Mexican Food         Shrimp  8/27/2019  ...     NaN  NaN      NaN
422  Valentine's Mexican Food    Pollo Asado  8/27/2019  ...     NaN  NaN      NaN

[423 rows x 66 columns]

In [ ]:
df1 = df[['Location','Burrito', "Date", "Cost", "Hunger", "Tortilla", "Temp", "Meat", "Fillings", "Uniformity", "Salsa", "Synergy", "Wrap", "overall"]]

In [ ]:
df1.dropna(inplace=True)
df1["Location"] = df1['Location'].str.replace('[{}]'.format(string.punctuation), '')
df1["Location"] = df1["Location"].str.title()
df1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                    Location      Burrito       Date  ...  Synergy  Wrap  overall
0          Donatos Taco Shop  California   1/18/2016  ...      4.0   4.0     3.80
1        Oscars Mexican Food  California   1/24/2016  ...      2.5   5.0     3.00
2        Oscars Mexican Food     Carnitas  1/24/2016  ...      3.0   5.0     3.00
3        Oscars Mexican Food  Carne asada  1/24/2016  ...      4.0   5.0     3.75
4               Pollos Maria   California  1/27/2016  ...      4.5   4.0     4.20
..                       ...          ...        ...  ...      ...   ...      ...
416  Valentines Mexican Food    Al Pastor  8/27/2019  ...      4.0   4.5     4.00
417  Valentines Mexican Food   California  8/27/2019  ...      5.0   5.0     4.25
420  Valentines Mexican Food   California  8/27/2019  ...      4.0   4.5     3.50
421  Valentines Mexican Food       Shrimp  8/27/2019  ...      5.0   2.0     4.00
422  Valentines Mexican Food  Pollo Asado  8/27/2019  ...      4.5   4.0     4.60

[356 rows x 14 columns]

In [ ]:
df1.Location.nunique()

87

In [ ]:
# get all restraurants with more than 10 reviews
df2 = df1.groupby(['Location']).filter(lambda x: len(x) > 5)
df2

                     Location             Burrito  ... Wrap  overall
8     Los Primos Mexican Food  Monster California  ...  2.0     3.90
11   Tonys Fresh Mexican Food    Chile verde pork  ...  1.0     3.00
12   Tonys Fresh Mexican Food          California  ...  4.0     3.90
13   Tonys Fresh Mexican Food      battered fish   ...  5.0     2.00
15                 Taco Stand          California  ...  4.5     4.20
..                        ...                 ...  ...  ...      ...
416   Valentines Mexican Food           Al Pastor  ...  4.5     4.00
417   Valentines Mexican Food          California  ...  5.0     4.25
420   Valentines Mexican Food          California  ...  4.5     3.50
421   Valentines Mexican Food              Shrimp  ...  2.0     4.00
422   Valentines Mexican Food         Pollo Asado  ...  4.0     4.60

[191 rows x 14 columns]

In [ ]:
df2.groupby(['Burrito']).count()

                            Location  Date  Cost  ...  Synergy  Wrap  overall
Burrito                                           ...
2 in 1                             3     3     3  ...        3     3        3
Adobada                            4     4     4  ...        4     4        4
Adobado                            1     1     1  ...        1     1        1
Al Pastor                          2     2     2  ...        2     2        2
Al pastor                          5     5     5  ...        5     5        5
Azteca                             1     1     1  ...        1     1        1
Baja monster                       2     2     2  ...        2     2        2
Breakfast                          1     1     1  ...        1     1        1
California                        38    38    38  ...       38    38       38
California                        12    12    12  ...       12    12       12
California - Chicken               2     2     2  ...        2     2        2
California - Pork Adobada          3     3     3  ...        3     3        3
California - Steak                 2     2     2  ...        2     2        2
California Chipotle                1     1     1  ...        1     1        1
California Everything             12    12    12  ...       12    12       12
California breakfast               1     1     1  ...        1     1        1
California chicken                 1     1     1  ...        1     1        1
California everything              3     3     3  ...        3     3        3
California everything mini         1     1     1  ...        1     1        1
Campeon                            2     2     2  ...        2     2        2
Carne asada                       15    15    15  ...       15    15       15
Carne asada everything             4     4     4  ...        4     4        4
Carnitas                          14    14    14  ...       14    14       14
Carnitas                           1     1     1  ...        1     1        1
Chicken                            1     1     1  ...        1     1        1
Chile Verde (pork)                 1     1     1  ...        1     1        1
Chile relleno and carnitas         1     1     1  ...        1     1        1
Chile verde pork                   1     1     1  ...        1     1        1
El Rusio                           1     1     1  ...        1     1        1
Fusion                             1     1     1  ...        1     1        1
Holy Moly                          5     5     5  ...        5     5        5
La Paz                             1     1     1  ...        1     1        1
Lobster                            1     1     1  ...        1     1        1
Local                             10    10    10  ...       10    10       10
Machaca                            1     1     1  ...        1     1        1
Mahi                               1     1     1  ...        1     1        1
Mixed                              1     1     1  ...        1     1        1
Monster California                 1     1     1  ...        1     1        1
Nutty                              1     1     1  ...        1     1        1
Philly                             1     1     1  ...        1     1        1
Pollo Asado                        1     1     1  ...        1     1        1
Pollo asado                        2     2     2  ...        2     2        2
Pork california                    1     1     1  ...        1     1        1
Quesa                              1     1     1  ...        1     1        1
Quesaburro                         1     1     1  ...        1     1        1
Shrimp                             3     3     3  ...        3     3        3
Supreme chicken                    1     1     1  ...        1     1        1
Surf & Turf                        9     9     9  ...        9     9        9
Surf and Turf                      1     1     1  ...        1     1        1
Surf and turf                      1     1     1  ...        1     1        1
Surf and turf                      1     1     1  ...        1     1        1
Surfin California                  7     7     7  ...        7     7        7
Tejano                             1     1     1  ...        1     1        1
battered fish                      1     1     1  ...        1     1        1

[54 rows x 13 columns]

In [ ]:
df_coolVals = df2.groupby(['Location']).mean()
df_coolVals

                              Cost    Hunger  ...      Wrap   overall
Location                                      ...
California Burritos       6.279167  4.062500  ...  4.325000  4.145833
Cancun Mexican  Seafood   6.733333  3.716667  ...  3.916667  4.100000
El Zarape                 6.906250  2.968750  ...  4.750000  3.466666
Lolitas Taco Shop         7.537500  3.391667  ...  4.000000  3.350000
Los Primos Mexican Food   6.860000  3.300000  ...  3.400000  2.680000
Los Tacos                 8.050000  3.241667  ...  4.150000  4.208333
Lucha Libre North Park    7.843750  3.466667  ...  4.062500  3.252083
Rigobertos Taco Shop      6.943750  3.593750  ...  3.562500  3.778125
Taco Stand                7.645200  3.384000  ...  4.140000  4.200000
Taco Villa                6.170000  3.454545  ...  3.927273  3.563636
Tonys Fresh Mexican Food  7.493333  3.500000  ...  3.666667  3.400000
Valentines Mexican Food   7.265625  3.312500  ...  3.656250  4.278125
Vallarta Express          7.395000  3.550000  ...  3.700000  3.460000

[13 rows x 11 columns]

In [ ]:
df_coolVals.to_csv("data1.csv")